---
chargen:
  achievements:
    created_character:
      type: story
      message: Created a character.
  allow_web_submit: false
  app_category: APP
  app_hold_status: HOLD
  app_resubmit_status: OPEN
  app_review_commands:
  - app %{name}
  - profile %{name}
  - bg %{name}
  - hooks %{name}
  - sheet %{name}
  approval_message: Congratulations!  Your application has been approved.  Type %xhonstage%xn
    to go forth and RP.  You may want to customize your character profile on the web
    portal.
  arrivals_category: New Arrivals
  bg_blurb: The prologue is your character's story up to the point where they arrive
    on  grid. It does not need to be a novel, but should identify key themes and tie
    your ancestry, heritage, background, and class together and suggest a possible
    direction for the character's story. That direction is not set in stone, and  can
    change as your story progresses.
  demographics_blurb: Demographics record your basic character info. Don't worry about
    class or  level or ancestry here, you'll set that when you do your sheet.
  desc_blurb: You can set both your main description, visible when people look at
    you, and a short description that shows your character at a glance. Like your
    prologue,  this does not have to be (and shouldn't be) a novel, just enough to
    get a  sense of what your character looks like.
  groups_blurb: Groups determine your character's affiliations. For now, put `Illuminators`.
  hooks_blurb: RP Hooks are interesting things about your character that others can
    hook into for RP. This could be an odd personality quirk, a reputation your character
    has, or anything else that might inspire someone to connect with you. Looking
    around at other character's sheets can be a good way to get inspiration for RP
    Hooks.
  hooks_required: true
  icon_blurb: Your profile icon appears in scenes and the character gallery to show
    your character at a glance. Providing a profile icon is optional. You can upload
    additional character images once you're approved for play.
  lastwill_blurb: The fate of idled-out characters is at the game admin's discretion,
    but you can register a preference with your character's 'last will'. You may ask
    to be killed off, or turned into a NPC, or whatever.
  permissions:
    manage_apps: Approve and reject character apps.
    view_bgs: Can view other characters' backgrounds
  post_approval_message: Please make sure they have a profile image for their log
    icon.
  rank_blurb: This game does not use ranks.
  registration_blurb: This game requires that players disclose their alts privately
    to game admins. See `help register` for more information.
  rejection_message: Sorry, your character could not be approved at the present time
    for the reasons described below.  Please see %xhhelp app%xn for help making changes
    and resubmitting, and contact the person handling your application if you have
    any questions.
  shortcuts:
    chargen: cg
    cg/back: cg/prev
    cg/previous: cg/prev
    hooks: hook
    hook/delete: hook/remove
    hook/add: hook/set
  stages:
    start:
      title: Chargen Commands
      text: You can do chargen either on the web portal (help web portal) or in-game.  They
        both have the same information - it's just a matter of preference. If you
        choose to use the in-game chargen, the %xccg%xn command will walk you through
        the necessary steps. You can go back and forth through the steps of chargen
        as much as you want using %xccg/next%xn and %xccg/prev%xn.
    app:
      title: App Review
      text: The `app` command is your friend during chargen.  It will alert you to
        things you may have forgotten to set.  %xrred%xn issues will almost certainly
        prevent your character from being approved (like forgetting to set your eye
        color).  %xyYellow%xn issues are warnings; they might actually be OK if it
        fits the character concept.
    demographics:
      help: demographics
    groups:
      help: groups
    prologue:
      help: backgrounds
    sheet_basic:
      help: pf2e_chargen
    sheet_abilities:
      help: pf2e_chargen_abilities
    desc:
      help: descriptions
    hooks:
      help: hooks
    registration:
      help: register
    handles:
      help: handles
    profile:
      help: profile
    lastwill:
      help: idle_out
    review:
      title: App Submission
      text: You've completed chargen!  Review your app one more time, and use `app/submit
        [<optional notes>]` to submit your character when ready.  The admins will
        make sure it's a good fit for the game's theme, that your sheet is in line
        with your background, and that you have not minmaxed or "dumpstatted". See
        `help apps` for additional help on the app review process.
  welcome_message: |-
    Please welcome %{name}, our latest %{position} to be approved!

    Profile: %{profile_link}

    RP Hooks:
    %{rp_hooks}
