---
datetime:
  date_and_time_entry_format_help: MMM DD YYYY hh:mm<am or pm>
  date_entry_format_help: MMM DD YYYY
  long_date_format: "%A, %B %d, %Y %l:%M%p"
  server_timezone: EST
  short_date_format: "%b %d %Y"
  time_format: "%l:%M%p"
