---
demographics:
  census_fields:
  - field: name
    width: 18
    title: Name
  - field: ancestry
    width: 13
    title: Ancestry
  - field: heritage
    width: 16
    title: Heritage
  - field: charclass
    width: 13
    title: Class
  demographics:
  - full name
  - gender
  - hair
  - eyes
  - skin
  - height
  - physique
  - played by
  - birthdate
  disable_auto_shortcuts: false
  editable_properties:
  - full name
  - gender
  - hair
  - physique
  genders:
    Male:
      possessive_pronoun: his
      subjective_pronoun: he
      objective_pronoun: him
      noun: man
    Female:
      possessive_pronoun: her
      subjective_pronoun: she
      objective_pronoun: her
      noun: woman
    Other:
      possessive_pronoun: their
      subjective_pronoun: they
      objective_pronoun: them
      noun: person
    Robot:
      possessive_pronoun: their
      subjective_pronoun: they
      objective_pronoun: them
      noun: robot
  groups:
    Region:
      desc: What region does your character call home?
      wiki: theme:regions
      values:
        Skyhaldborg: The rugged north.
        Dran: Harsh, wind-swept steppes.
        Alexandros: The Phoenix Kingdom.
        Myrddion: The kingdoms of Myrddion. # SPOILER: The kingdoms of the western Empire. 
        Bludgun: The nation of goblin-kin.
        Charn: The stygian domain of Charn. # SPOILER: The stygian domain of the Eastern Empire.
        Desolation: Home of an endless magical storm.
        Veyshan: Home of the desert nomads and the desert kingdoms. # SPOILER: Home of the desert nomads and the city-states of the One-Hundred and Four.
        Dragonier: The nation of the dragon kings.
        Jade Islands: The remains of a shattered land. # SPOILER: The remains of a shattered land, populated by the Kaltoi and merchant-circles
        Greatwoods: The ancient sildanyari kingdoms.
        Khazad Duin: The great citadel of the khazadi and its environs.
        Am'shere: The far-away jungles where the ciith dwell.
        Rune: The eccentric nation of wizards.
    Faith:
      desc: World philosophy your character ascribes to.
      wiki: 'theme:faiths'
      values:
        Holy Order of Ea: The teachings of the descendant faiths of the Aiglosian Empire's religion. # SPOILER: The teachings of the Millennial Empire and its nations.
        Green Word: The teachings of the peoples of the Greatwoods.
        Dragonlords: The tales and teachings of the dragons.
        Other: You have your own ideas on the world and how it works.
  help_text:
    played by: "%xcplayedby <actor>%xn - Your 'dream casting' for your character."
    physique: "%xcphysique <build/body type>%xn - athletic, wiry, slim, pudgy, etc."
    gender: "%xcgender <male/female/other>%xn"
    hair: "%xchair <hair color>%xn"
    eyes: "%xceyes <eye color>%xn"
    skin: "%xcskin <complexion>%xn"
    birthdate: "%xcbirthdate <mm/dd/yyy>%xn or %xcage <years>%xn"
    full name: "%xcfullname <name>%xn - Your character's full name."
  max_age: 1000
  min_age: 18
  nickname_field: ''
  nickname_format: "%{name} (%{nickname})"
  permissions:
    manage_demographics: Edit demographics on other players.
  private_properties: []
  required_properties:
  - hair
  - eyes
  - skin
  - height
  - physique
  - full name
  - gender
  - birthdate
  shortcuts:
    groups: group
    demographics: demographic
    birthday: birthdate
    actors: census played by
    actor: demographic/set played by=
    fullname: demographic/set full name=
    playedby: demographic/set played by=
    faith: group/set faith=
    region: group/set region=
    faith/info: group faith
    region/info: group region
