---
game:
  category: Other
  description: 'This is the Ares development site for conversion of Emblem of Ea
    from BrazilMUX to AresMUSH. It will never become public, and only admins and code testers will 
    ever have access to it.'
  name: Emblem of Ea Playtest
  public_game: false
  status: Sandbox
  website: playtest.emblemofeamush.net
