---
pf2e_skills:
  Acrobatics:
    key_abil: Dexterity
  Arcana:
    key_abil: Intelligence
    recall_knowledge: true
  Athletics:
    key_abil: Strength
  Crafting:
    key_abil: Intelligence
    recall_knowledge: true
  Deception:
    key_abil: Charisma
  Diplomacy:
    key_abil: Charisma
  Intimidation:
    key_abil: Charisma
  Medicine:
    key_abil: Wisdom
    recall_knowledge: true
  Nature:
    key_abil: Wisdom
    recall_knowledge: true
  Occultism:
    key_abil: Intelligence
    recall_knowledge: true
  Performance:
    key_abil: Charisma
  Religion:
    key_abil: Wisdom
    recall_knowledge: true
  Society:
    key_abil: Intelligence
    recall_knowledge: true
  Stealth:
    key_abil: Dexterity
  Survival:
    key_abil: Wisdom
  Thievery:
    key_abil: Dexterity
# Deity Lores
  Althean Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Angorite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Animusian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Caracorothan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Ceinaran Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Daeusite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Danan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Deimosian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Elunan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Gileadean Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Gunakharan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Illothan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Korite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Maugrimite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Navosian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Radan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Reosian Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Serrielite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Taaran Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Tarienite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Thulite Lore: 
    key_abil: Intelligence
    recall_knowledge: true
# City Lores
  Alexandria Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Bryn Myridorn Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Dun Mordren Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Tashraan Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Hextus Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Vandalheim Lore: 
    key_abil: Intelligence
    recall_knowledge: true
# Region Lores
  Alexandros Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Am'shere Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Bludgun Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Charn Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Dragonier Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Dran Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Desolation Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Greatwoods Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Jade Islands Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Khazad Duin Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Myrddion Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Rune Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Sturmvargd Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Vast Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Veyshan Lore:
    key_abil: Intelligence
    recall_knowledge: true
# Terrain Lores
  Aquatic Terrain Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Arctic Terrain Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Desert Terrain Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Forest Terrain Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Mountain Terrain Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Plains Terrain Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Sky Terrain Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Swamp Terrain Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Underground Terrain Lore: 
    key_abil: Intelligence
    recall_knowledge: true
# Creature Lores
  Angel Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Azata Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Beast Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Daemon Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Demon Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Devil Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Dragon Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Fey Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Fey Bullshit Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Genie Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Giant Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Hag Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Qlippoth Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Rakshasa Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Serpentfolk Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Spirit Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Vampire Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Velstrac Lore:
    key_abil: Intelligence
    recall_knowledge: true
# PC Ancestry and Heritage Lores
  Aesa Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Arvek Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Ashen One Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Bassin Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Changeling Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Ciith Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Dar Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Egalrin Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Gnome Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Goblin Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Human Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Kailli Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Khazad Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Niasa Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Oruch Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Sildanyar Lore:
    key_abil: Intelligence
    recall_knowledge: true
# General/Profession Lores
  Academia Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Accounting Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Alcohol Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Architecture Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Art Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Cartography Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Circus Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Curse Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Engineering Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Farming Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Fishing Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Fortune-Telling Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Games Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Genealogy Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Gladiatorial Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Guild Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Great Halls Lore:
    key_abil: Intelligence
    recall_knowledge: true
  Heraldry Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Herbalism Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Hunting Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Labor Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Legal Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Library Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Mercantile Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Midwifery Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Milling Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Mining Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Sailing Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Scouting Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Slayer Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Theater Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Underworld Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Warfare Lore: 
    key_abil: Intelligence
    recall_knowledge: true
# Crafting Lores
  Alchemy Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Artistry Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Blacksmithing Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Bookmaking Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Glassmaking Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Leatherworking Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Pottery Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Scribing Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Shipbuilding Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Stonemasonry Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Tailoring Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Tanning Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Weaving Lore: 
    key_abil: Intelligence
    recall_knowledge: true
  Woodworking Lore: 
    key_abil: Intelligence
    recall_knowledge: true
# Special/Class Specific Lores
  Bardic Lore:
    key_abil: Intelligence
    recall_knowledge: true