---
pf2e_subclass:
  get_genie_spell:
    Janni:
      2: Create Food
      5: Banishment
      8: Scintillating Pattern
    Djinni:
      2: Invisibility
      5: Illusory Scene
      8: Punishing Winds
    Efreeti:
      2: Enlarge
      5: Elemental Form
      8: Maze
    Marid:
      2: Water Walk
      5: Control Water
      8: Horrid Wilting
    Shaitan:
      2: Glitterdust
      5: Wall of Stone
      8: Earthquake
  Dragon Types:
    Black:
      element: acid
      shape: line
    Blue:
      element: electricity
      shape: line
    Green:
      element: poison
      shape: cone
    Red:
      element: fire
      shape: cone
    White:
      element: cold
      shape: cone
    Brass:
      element: fire
      shape: line
    Bronze:
      element: electricity
      shape: line
    Copper:
      element: acid
      shape: line
    Gold:
      element: fire
      shape: cone
    Silver:
      element: cold
      shape: cone
  wizard_school_spells:
    Abjuration:
      magic_stats:
        addspellbook: 
          1: 
          - Protective Ward
        gated_spell: school
    Conjuration: 
      magic_stats:
        addspellbook: 
          1: 
          - Augment Summoning
        ggated_spell: school
    Divination:
      magic_stats:
        addspellbook:
          1: 
          - Diviner's Sight
        gated_spell: school
    Enchantment:
      magic_stats:
        addspellbook:
          1: 
          - Charming Words
        gated_spell: school
    Evocation:
      magic_stats:
        addspellbook: 
          1: 
          - Force Bolt
        gated_spell: school
    Illusion:
      magic_stats:
        addspellbook:
          1:
          - Warped Terrain
        gated_spell: school
    Necromancy:
      magic_stats:
        addspellbook:
          1:
          - Call Of The Grave
        gated_spell: school
    Transmutation:
      magic_stats:
        addspellbook:
          1:
          - Physical Boost
        gated_spell: school
    Universalist:
      magic_stats:
      # This key overwrites the base wizard class key for this, this is intentional
        spellbook:
          cantrip: 10
          1: 6
        gated_feat: universalist

