---
pf2e_heritage:
# Arvek Heritages
  Elfbane:
    reaction:
    - Resist Elf Magic
    action: []
    defense: {}
    feat: []
    skills: []
    special: []
    traits: []
    attack: {}
  Runtboss:
    feat:
    - Group Coercion
    special:
    - Runtboss Arvek
    action: []
    attack: {}
    defense: {}
    reaction: []
    skills: []
    traits: []
  Smokeworker:
    defense:
      resistances:
        fire: 1
    special:
    - Smokeworker Arvek
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Warmarch:
    special:
    - Warmarch Arvek
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Warrenbred:
    special:
    - Warrenbred Arvek
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
# Bassin Heritages
  Gutsy:
    special:
    - Gutsy Bassin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Hillock:
    rest_HP_bonus: true
    special:
    - Hillock Bassin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Jinxed-bassin:
    special:
    - Jinxed Bassin
    action:
    - Jinx
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Nomadic:
    choose:
      language:
      - open
      - open
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Twilight:
    special:
    - Low-Light Vision
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Wildwood:
    special:
    - Wildwood Bassin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
# Ciith Heritage Feats
  Cliffscale:
    feat:
    - Combat Climber
    special:
    - Cliffscale Ciith
    traits: []
    skills: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Frilled:
    special:
    - Frilled Ciith
    action:
    - Threatening Approach
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Makar:
    movement:
      Swim: 15
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Sandstrider:
    defense:
      resistances:
        fire: 1
    special:
    - Sandstrider Ciith
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Unseen:
    circumstance: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
# Egalrin Heritage Feats
  Jinxed-egalrin:
    special:
    - Jinxed Egalrin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Mountainkeeper:
    magic_stats:
      innate_spell:
        cantrip:
        - 'Disrupt Undead'
        spell_trad: primal
    special:
    - Mountainkeeper Egalrin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Skyborn:
    special:
    - Skyborn Egalrin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Stormtossed:
    defense:
      resistances:
        electricity: 1
    special:
    - Stormtossed Egalrin
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Taloned:
    attack:
      Talons:
        damage: d4
        damage_type: S
        traits:
        - agile
        - finesse
        - unarmed
        - versatile_P
    action: []
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
# Gnome Heritage Feats
  Chameleon:
    circumstance: true
    traits: []
    special: []
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Fey-Touched:
    traits:
    - fey
    magic:
      choose:
        cantrip:
        - [ 'primal' ]
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
  Sensate:
    special:
    - Sensate Gnome
    circumstance: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Umbral:
    special:
    - Darkvision
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Wellspring:
    magic:
      choose:
        cantrip:
        - [ 'arcane', 'divine', 'occult' ]
    change_spell_trad: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
# Goblin Heritage Feats
  Charhide:
    defense:
      resistances:
        fire: 1
    special:
    - Charhide Goblin
    traits: []
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Irongut:
    special:
    - Irongut Goblin
    circumstance: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Razortooth:
    attack:
      Jaws:
        damage: d6
        damage_type: P
        traits:
        - finesse
        - unarmed
    action: []
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Snow:
    defense:
      resistances:
        cold: 1
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Unbreakable:
    ancestry_HP: 10
    special:
    - Unbreakable Goblin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
# Human Heritages
  Half-Oruch:
    traits:
    - oruch
    - half-oruch
    special:
    - Low-Light Vision
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
  Half-Sil:
    traits:
    - half-sil
    - sildanyar
    special:
    - Low-Light Vision
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
  Skilled:
    skills:
    - open
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    special: []
    traits: []
  Versatile:
    feat:
    - ancestry
    action: []
    attack: {}
    defense: {}
    reaction: []
    skills: []
    special: []
    traits: []
# Kailli Heritages
  Deep Kailli:
    traits: []
    special:
    - Darkvision
    skills: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Desert:
    defense:
      resistances:
        fire: 1
    traits: []
    special: []
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Longsnout:
    traits: []
    special:
    - Scent (imprecise)
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Sewer:
    traits: []
    special:
    - Sewer Kailli
    skills:
    - Intimidation
    feat: []
    action: []
    reaction: []
    attack: {}
  Shadow:
    traits: []
    special:
    - Shadow Kailli
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
# Khazad Heritages
  Ancient-Blooded:
    reaction: 'Call On Ancient Blood'
    action: []
    attack: {}
    traits: []
    special: []
    skills: []
    feat: []
    defense: {}
  Anvil:
    traits: []
    special: []
    skills:
    - Crafting
    choose:
      Heritage Feats:
      - Specialty Crafting
      - Specialty Crafting
    action: []
    reaction: []
    defense: {}
    attack: {}
  Death Warden:
    circumstance: true
    traits: []
    special: []
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Forge:
    defense:
      resistances:
        fire: 1
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Rock:
    circumstance: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Strong-Blooded:
    defense:
      resistances:
        poison: 1
    circumstance: true
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
# Oruch Heritages
  Badlands:
    traits: []
    special:
    - Badlands Oruch
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Deep Oruch:
    feat:
    - Terrain Expertise/Underground
    - Combat Climber
    traits: []
    special: []
    skills: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Hold-Scarred:
    ancestry_HP: 12
    feat:
    - Diehard
    action: []
    attack: {}
    defense: {}
    reaction: []
    skills: []
    special: []
    traits: []
  Rainfall:
    circumstance: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
# Sildanyar Heritages
  Arctic:
    traits: []
    defense:
      resistances:
        cold: 1
    circumstance: true
    special: []
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Cavern:
    traits: []
    special:
    - Darkvision
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Seer:
    magic:
      innate_spell:
        cantrip:
        - 'Detect Magic'
        spell_trad: arcane
    action:
    - Identify Magic
    - Decipher Writing
    action_bonus: 1
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Whisper:
    circumstance: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Woodland:
    circumstance: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
# Versatile Heritages
  Aesa:
    rare: true
    traits:
    - aesa
    special:
    - Low-Light Vision
    change_vision: true
    action: []
    attack: {}
    reaction: []
    skills: []
    feat: []
    defense: {}
  Ashen One:
    rare: true
    traits:
    - ashen one
    special:
    - Low-Light Vision
    defense: {}
    change_vision: true
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Changeling:
    rare: true
    traits:
    - changeling
    special:
    - Low-Light Vision
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
    change_vision: true
  Dar:
    rare: true
    traits:
    - Dar
    special:
    - Low-Light Vision
    - Negative Healing
    change_vision: true
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Niasa:
    rare: true
    traits:
    - niasa
    special:
    - Low-Light Vision
    change_vision: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []