---
pf2e_ancestry:
  Arvek Nar:
    HP: 8
    Size: M
    Speed: 25
    abl_boosts:
    - Constitution
    - Intelligence
    - open
    abl_flaws: Wisdom
    languages:
    - Tradespeak
    - Gobber
    traits:
    - arvek
    - humanoid
    special:
    - darkvision
    heritages:
    - Aasimar
    - Ashen One
    - Changeling
    - Dar
    - Elfbane
    - Runtboss
    - Smokeworker
    - Tiefling
    feats:
      1:
      - Alchemical Scholar
      - Arvek Lore
      - Arvek Weapon Familiarity
      - Leech-Clipper
      - Remorseless Lash
      - Vigorous Health
      5:
      - Agonizing Rebuke
      - Arvek Weapon Discipline
      - Expert Drill Sergeant
      - Fey Influence
      - Formation Training
      9:
      - Pride In Arms
      13:
      - Arvek Weapon Expertise
      - Formation Master
      17:
      - "Azaersi's Roads"
  Gnome:
    HP: 8
    Size: S
    Speed: 25
    abl_boosts:
    - Constitution
    - Charisma
    - open
    abl_flaw: Strength
    languages:
    - Tradespeak
    - Gnomish
    - Sylvan
    traits:
    - gnome
    - humanoid
    special:
    - Low-Light Vision
    heritages:
    - Aasimar
    - Ashen One
    - Chameleon
    - Changeling
    - Dar
    - Fey-Touched
    - Sensate
    - Tiefling
    - Umbral
    - Vivacious
    - Wellspring
    feats:
      1:
      - Animal Accomplice
      - Burrow Elocutionist
      - Empathetic Plea
      - Fey Fellowship
      - First World Magic
      - Gnome Obsession
      - Gnome Polyglot
      - Gnome Weapon Familiarity
      - Grim Insight
      - Illusion Sense
      - Inventive Offensive
      - Life-Giving Magic
      - Natural Performer
      - Razzle-Dazzle
      - Theoretical Acumen
      - Unexpected Shift
      - Vibrant Display
      5:
      - Animal Elocutionist
      - Eclectic Obsession
      - Energized Font
      - Fey Influence
      - Gnome Weapon Innovator
      - Intuitive Illusions
      - Natural Illusionist
      - Project Persona
      9:
      - Cautious Curiosity
      - First World Adept
      - Fortuitous Shift
      - Life Leap
      - Vivacious Conduit
      13:
      - Gnome Weapon Expertise
      - Instinctive Obfuscation
      17:
      - Homeward Bound
  Gobber:
    HP: 6
    Size: S
    Speed: 25
    abl_boosts:
    - Dexterity
    - Charisma
    - open
    abl_flaw: Wisdom
    languages:
    - Tradespeak
    - Gobber
    traits:
    - goblin
    - humanoid
    special:
    - darkvision
    heritages:
    - Aasimar
    - Ashen One
    - Changeling
    - Charhide
    - Dar
    - Irongut
    - Razortooth
    - Snow
    - Tailed
    - Tiefling
    - Treedweller
    - Unbreakable
    feats:
      1:
      - Bouncy Gobber
      - Burn It!
      - City Scavenger
      - Extra Squishy
      - Fang Sharpener
      - Gobber Lore
      - Gobber Shuttle
      - Gobber Song
      - Gobber Weapon Familiarity
      - Hard Tail
      - Junk Tinker
      - Rough Rider
      - Twitchy
      - Very Sneaky
      5:
      - Ankle Bite
      - Chosen of Lamashtu
      - Fey Influence
      - Gobber Weapon Frenzy
      - Kneecap
      - Loud Singer
      - Tail Spin
      - Torch Gobber
      - "Tree Climber (Gobber)"
      - Vandal
      9:
      - Cave Climber
      - Cling
      - Freeze It!
      - Hungry Gobber
      - Roll With It
      - Scalding Spit
      - Skittering Scuttle
      13:
      - Gobber Weapon Expertise
      - Unbreakable-er Gobber
      - "Very, Very Sneaky"
      17:
      - Reckless Abandon
  Egalrin:
    HP: 6
    Size: M
    abl_boosts:
    - Dexterity
    - open
    languages:
    - Tradespeak
    - Egalrin
    traits:
    - egalrin
    - humanoid
    special:
    - Low-Light Vision
    attack:
      Beak:
        damage: 1d6
        damage_type: P
        group: brawling
        traits:
        - finesse
        - unarmed
    heritages:
    - Aasimar
    - Ashen One
    - Changeling
    - Dar
    - Jinxed-egalrin
    - Mountainkeeper
    - Skyborn
    - Stormtossed
    - Taloned
    - Tiefling
    feats:
      1:
      - Egalrin Lore
      - Egalrin Weapon Familiarity
      - "Scavenger's Search"
      - Squawk!
      - "Storm's Lash"
      5:
      - Eat Fortune
      - Egalrin Weapon Study
      - Fey Influence
      - Long-Nosed Form
      - One-Toed Hop
      9:
      - Eclectic Sword Training
      - Soaring Flight
      13:
      - Egalrin Weapon Expertise
      17:
      - Great Egalrin Form
  Human:
    HP: 8
    Size: M
    Speed: 25
    abl_boosts:
    - open
    - open
    abl_flaw: ""
    languages:
    - Tradespeak
    traits:
    - human
    - humanoid
    heritages:
    - Aasimar
    - Ashen One
    - Changeling
    - Dar
    - Half-Sil
    - Half-Oruch
    - Skilled
    - Tiefling
    - Versatile
    - Wintertouched
    feats:
      1:
      - Adapted Cantrip
      - Arcane Tattoos
      - Cooperative Nature
      - Courteous Comeback
      - "Devil's Advocate"
      - Dragon Spit
      - General Training
      - Gloomseer
      - Haughty Obstinacy
      - Keep Up Appearance
      - Know Oneself
      - Natural Ambition
      - Natural Skill
      - Quah Bond
      - Saoc Astrology
      - Tupilaq Carver
      - Unconventional Weaponry
      - Viking Shieldbearer
      - Witch Warden
      5:
      - Adaptive Adept
      - Clever Improviser
      - Darkseer
      - Fey Influence
      - Ornate Tattoo
      - Sense Allies
      - Wavetouched Paragon
      9:
      - Cooperative Soul
      - Dragon Prince
      - Group Aid
      - Hardy Traveler
      - Heir of the Saoc
      - Incredible Improvisation
      - Multitalented
      - Shory Aeromancer
      - Virtue-Forged Tattoos
      13:
      - Advanced General Training
      - Bounce Back
      - Irriseni Ice-Witch
      - Shadow Pact
      - Shory Aerialist
      - Stubborn Persistence
      - Unconventional Expertise
      17:
      - Heroic Presence
  Khailli:
    HP: 6
    Size: S
    abl_boosts:
    - Dexterity
    - Intelligence
    - open
    abl_flaws: Strength
    languages:
    - Tradespeak
    - Ysoki
    traits:
    - uncommon
    - humanoid
    - ratfolk
    special:
    - Low-Light Vision
    heritages:
    - Aasimar
    - Ashen One
    - Changeling
    - Dar
    - Deep Rat
    - Desert Rat
    - Longsnout Rat
    - Sewer Rat
    - Shadow Rat
    - Snow Rat
    - Tiefling
    - Tunnel Rat
    feats:
      1:
      - Cheek Pouches
      - Pack Rat
      - Rat Familiar
      - Ratfolk Lore
      - Ratspeak
      - Skull Creeper
      - Tinkering Fingers
      - Vicious Incisors
      - Warren Friend
      - Warren Navigator
      5:
      - Cornered Fury
      - Fey Influence
      - Gnaw
      - Lab Rat
      - Plague Sniffer
      - Quick Stow (Ratfolk)
      - Rat Magic
      - Ratfolk Roll
      9:
      - Big Mouth
      - Overcrowd
      - Rat Form
      13:
      - Shinstabber
      - Skittering Sneak
      - Warren Digger
      - Ratfolk Growth
  Khazad:
    HP: 10
    Size: M
    Speed: 20
    abl_boosts:
    - Constitution
    - Wisdom
    - open
    abl_flaw: Charisma
    languages:
    - Khazdul
    - Tradespeak
    traits:
    - khazad
    - humanoid
    special:
    - Darkvision
    heritages:
    - Aasimar
    - Ancient-Blooded
    - Anvil
    - Ashen One
    - Changeling
    - Dar
    - Death Warden
    - Elemental Heart
    - Forge
    - Oathkeeper
    - Rock
    - Strong-Blooded
    - Tiefling
    feats:
      1:
      - Avenge In Glory
      - Clan's Edge
      - Khazadi Doughtiness
      - Khazadi Lore
      - Khazadi Weapon Familiarity
      - Eye For Treasure
      - "Forge-Day's Rest"
      - Rock Runner
      - Stonecunning
      - Surface Culture
      - Unburdened Iron
      - Vengeful Hatred
      5:
      - Boulder Roll
      - Clan Protector
      - Defy the Darkness
      - Fey Influence
      - Khazadi Reinforcement
      - Khazadi Weapon Cunning
      - Protective Sheath
      - Sheltering Slab
      - "Tomb-Watcher's Glare"
      9:
      - Battleforger
      - Echoes in Stone
      - Energy Blessed
      - "Heroes' Call"
      - Kneel for No God
      - "Mountain's Stoutness"
      - Returning Throw
      - Stone Bones
      - Stonewalker
      13:
      - Khazadi Weapon Expertise
      - Telluric Power
      17:
      - Stonegate
  Lizardfolk:
    HP: 8
    Size: M
    Speed: 25
    abl_boosts:
    - Strength
    - Wisdom
    - open
    abl_flaw: Intelligence
    languages:
    - Tradespeak
    - Draconic
    traits:
    - lizardfolk
    - humanoid
    attack:
      Claws:
        damage: 1d4
        damage_type: S
        traits:
        - agile
        - finesse
        - unarmed
    bonus_feats:
    - Breath Control
    heritages:
    - Aasimar
    - Ashen One
    - Changeling
    - Cliffscale
    - Dar
    - Frilled
    - Sandstrider
    - Sith-Makar
    - Unseen
    - Tiefling

    feats:
      1:
      - Lizardfolk Lore
      - Marsh Runner
      - Parthenogenetic Hatchling
      - Razor Claws
      - Reptile Speaker
      - Sharp Fangs
      - Tail Whip
      5:
      - Envenom Fangs
      - Fey Influence
      - "Gecko's Grip"
      - Iruxi Unarmed Cunning
      - Shed Tail
      - Swift Swimmer
      9:
      - Terrain Advantage
      13:
      - Iruxi Unarmed Expertise
  Lucht Siuil:
    HP: 6
    Size: S
    Speed: 25
    able_boosts:
    - Dexterity
    - Wisdom
    - open
    abl_flaw: Strength
    languages:
    - Tradespeak
    - Lucht
    traits:
    - Lucht
    - humanoid
    special:
    - keen eyes
    heritages:
    - Aasimar
    - Ashen One
    - Changeling
    - Dar
    - Gutsy
    - Hillock
    - Jinxed-lucht
    - Nomadic
    - Observant
    - Tiefling
    - Twilight
    - Wildwood
    feats:
      1:
      - Adroit Manipulation
      - Distracting Shadows
      - Folksy Patter
      - Innocuous
      - Intuitive Cooperation
      - Lucht Lore
      - Lucht Luck
      - Lucht Weapon Familiarity
      - Prairie Rider
      - Sure Feet
      - Titan Slinger
      - Unassuming Dedication
      - Unfettered Lucht
      - Watchful Lucht
      5:
      - Cultural Adaptability
      - Easily Dismissed
      - Fey Influence
      - Lucht Ingenuity
      - Lucht Weapon Trickster
      - "Shared Luck (Lucht)"
      - Step Lively
      9:
      - Cunning Climber
      - Dance Underfoot
      - Fade Away
      - Guiding Luck
      - Helpful Lucht
      - Irrepressible
      - Unhampered Passage
      13:
      - Ceaseless Shadows
      - Cobble Dancer
      - Lucht Weapon Expertise
      - "Incredible Luck (Lucht)"
      - Toppling Dance
      17:
      - Shadow Self
  Oruch:
    HP: 10
    Size: M
    Speed: 25
    abl_boosts:
    - Strength
    - open
    languages:
    - Tradespeak
    - Yrch
    traits:
    - oruch
    - humanoid
    special:
    - darkvision
    heritages:
    - Aasimar
    - Ashen One
    - Badlands
    - Changeling
    - Dar
    - Deep
    - Hold-Scarred
    - Rainfall
    - Tiefling
    feats:
      1:
      - Beast Trainer
      - Iron Fists
      - Oruch Ferocity
      - Oruch Lore
      - Oruch Superstition
      - Oruch Weapon Familiarity
      - Tusks
      5:
      - Athletic Might
      - Bloody Blows
      - Fey Influence
      - Hold Mark
      - Oruch Weapon Carnage
      - Victorious Vigor
      9:
      - "Death's Drums"
      - Pervasive Superstition
      - Undying Ferocity
      13:
      - Ferocious Beasts
      - Incredible Ferocity
      - Oruch Weapon Expertise
      - Spell Devourer
      17:
      - Rampaging Ferocity
  Sildanyar:
    HP: 6
    Size: M
    Speed: 30
    abl_boosts:
    - Dexterity
    - Intelligence
    - open
    abl_flaw: Constitution
    languages:
    - Tradespeak
    - Silya
    traits:
    - sildanyar
    - humanoid
    special:
    - Low-Light Vision
    heritages:
    - Aasimar
    - Ashen One
    - Ancient
    - Arctic
    - Cavern
    - Changeling
    - Dar
    - Desert
    - Seer
    - Tiefling
    - Whisper
    - Woodland
    feats:
      1:
      - Ancestral Linguistics
      - Ancestral Longevity
      - Elemental Wrath
      - Forlorn
      - Know Your Own
      - Nimble Elf
      - Otherworldly Magic
      - Share Thoughts
      - Silya Aloofness
      - Silya Lore
      - Silya Verve
      - Silya Weapon Familiarity
      - Unwavering Mien
      - Wildborn Magic
      - Woodcraft
      5:
      - Ageless Patience
      - Ancestral Suspicion
      - Defiance Unto Death
      - Fey Influence
      - Forest Stealth
      - Martial Experience
      - Silya Instincts
      - Silya Weapon Elegance
      - Wildborn Adept
      9:
      - Brightness Seeker
      - Elf Step
      - Expert Longevity
      - Otherworldly Acumen
      - Sense Thoughts
      - Tree Climber (Elf)
      13:
      - Avenge Ally
      - Silya Weapon Expertise
      - Universal Longevity
      - Wandering Heart
      17:
      - Magic Rider
