---
pf2e_subclass:
  get_genie_spell:
    Janni:
      2: Create Food
      5: Banishment
      8: Scintillating Pattern
    Djinni:
      2: Invisibility
      5: Illusory Scene
      8: Punishing Winds
    Efreeti:
      2: Enlarge
      5: Elemental Form
      8: Maze
    Marid:
      2: Water Walk
      5: Control Water
      8: Horrid Wilting
    Shaitan:
      2: Glitterdust
      5: Wall of Stone
      8: Earthquake
  Dragon Types:
    Black:
      element: acid
      shape: line
    Blue:
      element: electricity
      shape: line
    Green:
      element: poison
      shape: cone
    Red:
      element: fire
      shape: cone
    White:
      element: cold
      shape: cone
    Brass:
      element: fire
      shape: line
    Bronze:
      element: electricity
      shape: line
    Copper:
      element: acid
      shape: line
    Gold:
      element: fire
      shape: cone
    Silver:
      element: cold
      shape: cone
  wizard_school_spells:
    Abjuration:
      magic_stats:
        addspellbook: 
          1: 
          - Protective Ward
        school_spell: abjuration
    Conjuration: 
      magic_stats:
        addspellbook: 
          1: 
          - Augment Summoning
        school_spell: conjuration
    Divination:
      magic_stats:
        addspellbook:
          1: 
          - Diviner's Sight
        school_spell: divination
    Enchantment:
      magic_stats:
        addspellbook:
          1: 
          - Charming Words
        school_spell: enchantment
    Evocation:
      magic_stats:
        addspellbook: 
          1: 
          - Force Bolt
        school_spell: evocation
    Illusion:
      magic_stats:
        addspellbook:
          1:
          - Warped Terrain
        school_spell: illusion
    Necromancy:
      magic_stats:
        addspellbook:
          1:
          - Call Of The Grave
        school_spell: necromancy
    Transmutation:
      magic_stats:
        addspellbook:
          1:
          - Physical Boost
        school_spell: transmutation
    Universalist:
      magic_stats:
      # This key overwrites the base wizard class key for this, this is intentional
        spellbook:
          cantrip: 10
          1: 6
        school_feat: true

