---
pf2e_armor:
  Explorer's Clothing:
    category: unarmored
    traits:
    - comfort
    level: 0
    price: 10
    dex_cap: 5
    ac_bonus: 0
    bulk: 0.1
    check_penalty: 0
    speed_penalty: 0
    min_str: 8
    group: Cloth
  Padded:
    category: light
    traits:
    - comfort
    level: 0
    price: 20
    ac_bonus: 1
    dex_cap: 3
    check_penalty: 0
    speed_penalty: 0
    min_str: 10
    bulk: 0.1
    group: Cloth
  Leather:
    category: light
    traits: []
    level: 0
    price: 300
    ac_bonus: 2
    dex_cap: 3
    check_penalty: -1
    speed_penalty: 0
    min_str: 12
    bulk: 1
    group: Leather
  Studded Leather:
    category: light
    traits: []
    level: 0
    price: 20
    ac_bonus: 1
    dex_cap: 3
    check_penalty: -1
    speed_penalty: 0
    min_str: 10
    bulk: 1
    group: Cloth
  Chain Shirt:
    category: light
    traits:
    - flexible
    - noisy
    level: 0
    price: 500
    ac_bonus: 2
    dex_cap: 3
    check_penalty: -1
    speed_penalty: 0
    min_str: 2
    bulk: 1
    group: Chain
  Hide:
    category: medium
    traits: []
    level: 0
    price: 200
    ac_bonus: 3
    dex_cap: 2
    check_penalty: -2
    speed_penalty: -5
    min_str: 14
    bulk: 2
    group: Leather
  Scale:
    category: medium
    traits: []
    level: 0
    price: 400
    ac_bonus: 3
    dex_cap: 2
    check_penalty: -2
    speed_penalty: -5
    min_str: 14
    bulk: 2
    group: Composite
  Chain Mail:
    category: medium
    traits:
    - flexible
    - noisy
    level: 0
    price: 600
    ac_bonus: 4
    dex_cap: 1
    check_penalty: -2
    speed_penalty: -5
    min_str: 16
    bulk: 2
    group: Chain
  Breastplate:
    category: medium
    traits: []
    level: 0
    price: 800
    ac_bonus: 4
    dex_cap: 1
    check_penalty: -2
    speed_penalty: -5
    min_str: 16
    bulk: 2
    group: Plate
  Splint Mail:
    category: heavy
    traits: []
    level: 1
    price: 1300
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 3
    group: Composite
  Half Plate:
    category: heavy
    traits: []
    level: 1
    price: 1800
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 3
    group: Plate
  Full Plate:
    category: heavy
    traits:
    - bulwark
    level: 02
    price: 3000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
